# Generated by GPT

import os
import re
import json
import argparse
from statistics import mean, stdev, median

# Regex patterns
sigkill_pattern = re.compile(r"SIGKILL: added to TGID (\d+) PID (\d+) at (\d+)")
exit_pattern = re.compile(r"EXIT: TGID (\d+) PID (\d+) at (\d+)")


TRIM_PERCENT = 5


def trim_values(values, percent):
    """Trim bottom and top X% of values."""
    if not values:
        return []

    values = sorted(values)
    n = len(values)

    trim_count = int(n * percent / 100)

    # avoid over-trimming small datasets
    if n < 10 or trim_count == 0:
        return values

    return values[trim_count:n - trim_count]


def compute_stats(values):
    """Compute avg, std, and median for a list of values (trimmed)."""

    values = trim_values(values, TRIM_PERCENT)

    if not values:
        return {"avg": 0.0, "std": 0.0, "median": 0.0}

    avg_val = mean(values)
    std_val = stdev(values) if len(values) > 1 else 0.0
    med_val = median(values)

    return {
        "avg": avg_val,
        "std": std_val,
        "median": med_val
    }


def process_log(log_file):
    sigkill_times = {}
    response_times = []

    with open(log_file, "r") as f:
        for line in f:
            m = sigkill_pattern.search(line)
            if m:
                tgid, pid, ts = int(m.group(1)), int(m.group(2)), int(m.group(3))
                sigkill_times[pid] = ts
                continue

            m = exit_pattern.search(line)
            if m:
                tgid, pid, ts = int(m.group(1)), int(m.group(2)), int(m.group(3))
                if pid in sigkill_times:
                    response_times.append(ts - sigkill_times[pid])

    return response_times


def main():
    parser = argparse.ArgumentParser(description="Process SIGKILL/EXIT logs")
    parser.add_argument("log_dir", help="Directory containing log files")
    parser.add_argument("num_traces", type=int, help="Number of log files")
    args = parser.parse_args()

    log_dir = os.path.join(args.log_dir, "logs")
    output_file = os.path.join(log_dir, "final.json")

    all_response_times = []

    for i in range(1, args.num_traces + 1):
        log_file = os.path.join(log_dir, f"log_{i}.txt")

        if not os.path.exists(log_file):
            print(f"Skipping missing file: {log_file}")
            continue

        response_times = process_log(log_file)
        all_response_times.extend(response_times)

    stats = compute_stats(all_response_times)

    with open(output_file, "w") as f:
        json.dump(stats, f, indent=4)


if __name__ == "__main__":
    main()