# Generated by GPT

import os
import re
import json
import argparse
from copy import deepcopy
from math import sqrt

entry_pattern = re.compile(r"--->(\w+)\(\)\s*{")
exit_pattern = re.compile(r"<---(\w+)\(\)\s+inc=\s*(\d+)\s*ns,\s*exc=\s*(\d+)\s*ns\s*}")

TRIM_PERCENT = 5


def initialize_vals(node):
    if node["inc_ns"] is None or node["exc_ns"] is None:
        return None

    node["inc_ns_vals"] = [node["inc_ns"]]
    node["exc_ns_vals"] = [node["exc_ns"]]

    new_children = []
    for c in node["children"]:
        cc = initialize_vals(c)
        if cc:
            new_children.append(cc)
    node["children"] = new_children

    return node


def merge_trees(t1, t2):
    for i, n2 in enumerate(t2):
        if i < len(t1) and t1[i]["function"] == n2["function"]:
            n1 = t1[i]
            n1["inc_ns_vals"].extend(n2["inc_ns_vals"])
            n1["exc_ns_vals"].extend(n2["exc_ns_vals"])
            merge_trees(n1["children"], n2["children"])
        else:
            t1.append(deepcopy(n2))


def compute_stats(node):

    def stddev(lst):
        if not lst:
            return 0.0
        m = sum(lst) / len(lst)
        return sqrt(sum((x - m) ** 2 for x in lst) / len(lst))

    def median(lst):
        if not lst:
            return 0.0
        lst = sorted(lst)
        n = len(lst)
        mid = n // 2
        return (lst[mid - 1] + lst[mid]) / 2 if n % 2 == 0 else lst[mid]

    def trim(lst, p):
        if not lst:
            return []
        lst = sorted(lst)
        n = len(lst)
        k = int(n * p / 100)
        if n < 10 or k == 0:
            return lst
        return lst[k:n - k]

    inc_vals = trim([x for x in node["inc_ns_vals"] if x is not None], TRIM_PERCENT)
    exc_vals = trim([x for x in node["exc_ns_vals"] if x is not None], TRIM_PERCENT)

    return {
        "function": node["function"],
        "inc_ns_avg": sum(inc_vals) / len(inc_vals) if inc_vals else 0.0,
        "inc_ns_std": stddev(inc_vals),
        "inc_ns_median": median(inc_vals),
        "exc_ns_avg": sum(exc_vals) / len(exc_vals) if exc_vals else 0.0,
        "exc_ns_std": stddev(exc_vals),
        "exc_ns_median": median(exc_vals),
        "children": [compute_stats(c) for c in node["children"]]
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("log_dir")
    parser.add_argument("num_traces", type=int)
    args = parser.parse_args()

    log_dir = os.path.join(args.log_dir, "traces")
    output_file = os.path.join(log_dir, "final.json")

    aggregated_roots = []

    for i in range(1, args.num_traces + 1):
        log_file = os.path.join(log_dir, f"trace_{i}.txt")
        if not os.path.exists(log_file):
            continue

        stack = []
        root_nodes = []

        start = False
        root_seen = False

        with open(log_file) as f:
            for line_num, line in enumerate(f, 1):
                line = line.strip()

                # 🚀 wait for first do_execveat_common entry
                if not start:
                    if "--->do_execveat_common" in line:
                        start = True
                    else:
                        continue

                entry_match = entry_pattern.search(line)
                exit_match = exit_pattern.search(line)

                if entry_match:
                    func = entry_match.group(1)

                    node = {
                        "function": func,
                        "inc_ns": None,
                        "exc_ns": None,
                        "children": []
                    }

                    if stack:
                        stack[-1]["children"].append(node)
                    else:
                        root_nodes.append(node)

                    stack.append(node)

                elif exit_match:
                    func, inc, exc = exit_match.groups()

                    if not stack:
                        continue

                    top = stack[-1]

                    if top["function"] != func:
                        continue

                    node = stack.pop()
                    node["inc_ns"] = int(inc)
                    node["exc_ns"] = int(exc)

                    # 🛑 STOP CONDITION: root finished
                    if func == "do_execveat_common":
                        root_seen = True
                        break

        # clean tree
        clean_roots = []
        for n in root_nodes:
            c = initialize_vals(n)
            if c:
                clean_roots.append(c)

        if not aggregated_roots:
            aggregated_roots = deepcopy(clean_roots)
        else:
            merge_trees(aggregated_roots, clean_roots)

    final = [compute_stats(r) for r in aggregated_roots]

    with open(output_file, "w") as f:
        json.dump(final, f, indent=4)


if __name__ == "__main__":
    main()