# Generated by GPT

import os
import json
import numpy as np
import matplotlib.pyplot as plt
import sys

if len(sys.argv) != 3:
    print("Usage: python3 plot.py <test_name> <thread_num>")
    sys.exit(1)

test_name = sys.argv[1]
THREAD = int(sys.argv[2])

num_threads = np.array([THREAD])

TARGET_FUNCTIONS = ["de_thread", "do_execveat_common"]


def safe_load_json(path):
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return None


def find_function(node_list, target):
    if not isinstance(node_list, list):
        return None

    for node in node_list:
        if not isinstance(node, dict):
            continue

        if node.get("function") == target:
            return node

        res = find_function(node.get("children", []), target)
        if res:
            return res

    return None


def extract_data(base_dir, func_name, mode, opt_on):

    zap, response, waiting = [], [], []

    for n in num_threads:

        folder_path = os.path.join(
            base_dir,
            str(n),
            "optimized" if opt_on else "original"
        )

        trace_file = os.path.join(folder_path, "traces", "final.json")
        log_file = os.path.join(folder_path, "logs", "final.json")

        if not (os.path.isfile(trace_file) and os.path.isfile(log_file)):
            return (np.array([np.nan]),
                    np.array([np.nan]),
                    np.array([np.nan]))

        data = safe_load_json(trace_file)
        log_data = safe_load_json(log_file)

        if data is None or log_data is None:
            return (np.array([np.nan]),
                    np.array([np.nan]),
                    np.array([np.nan]))

        func_node = find_function(data, func_name)
        zap_node = find_function(data, "zap_other_threads")

        if func_node is None or zap_node is None:
            return (np.array([np.nan]),
                    np.array([np.nan]),
                    np.array([np.nan]))

        try:
            if mode == "median":
                func_total = func_node["inc_ns_median"]
                zap_time = zap_node["inc_ns_median"]
                log_key = "median"
            else:
                func_total = func_node["inc_ns_avg"]
                zap_time = zap_node["inc_ns_avg"]
                log_key = "avg"

            response_time = log_data.get(log_key, np.nan)

            if response_time is None:
                response_time = np.nan

            waiting_time = func_total - (zap_time + response_time)

        except Exception:
            return (np.array([np.nan]),
                    np.array([np.nan]),
                    np.array([np.nan]))

        return (
            np.array([zap_time]),
            np.array([response_time]),
            np.array([waiting_time])
        )


# -------------------- IMPROVED PLOTTING --------------------

def plot_stack(ax, x, zap, resp, wait, colors, label, width, offset):

    if np.isnan(zap) or np.isnan(resp) or np.isnan(wait):
        ax.text(x + offset, 0, "MISSING",
                ha='center', color='#ef4444', fontsize=11, fontweight='bold')
        return

    xpos = x + offset

    # Plot bars with edge colors for depth
    ax.bar(xpos, zap, width, color=colors["zap"], edgecolor='white', 
           linewidth=2, label=f"zap ({label})", alpha=0.9)
    ax.bar(xpos, resp, width, bottom=zap, color=colors["response"], 
           edgecolor='white', linewidth=2, label=f"response ({label})", alpha=0.9)
    ax.bar(xpos, wait, width, bottom=zap + resp, color=colors["waiting"], 
           edgecolor='white', linewidth=2, label=f"waiting ({label})", alpha=0.9)

    def add(y, val):
        if val <= 0:
            return
        ax.text(xpos, y, f"{val:.0f}", ha='center', va='center',
                fontsize=10, fontweight='600', color='white',
                bbox=dict(boxstyle='round,pad=0.4', facecolor='black', 
                         alpha=0.35, edgecolor='none'))

    add(zap / 2, zap)
    add(zap + resp / 2, resp)
    add(zap + resp + wait / 2, wait)


def plot_simple(ax, x, zap, resp, wait, color, label, width, offset):

    if np.isnan(zap) or np.isnan(resp) or np.isnan(wait):
        ax.text(x + offset, 0, "MISSING",
                ha='center', color='#ef4444', fontsize=11, fontweight='bold')
        return

    total = zap + resp + wait
    xpos = x + offset

    # Plot bar with edge for depth
    ax.bar(xpos, total, width, color=color, edgecolor='white', 
           linewidth=2, label=f"total ({label})", alpha=0.9)
    ax.text(xpos, total + total * 0.03, f"{total:.0f}", ha='center', 
            fontsize=11, fontweight='700', color=color)


def plot_test_function(test_name, func_name, mode):

    base_path = f"./results/{test_name}"
    if not os.path.isdir(base_path):
        print(f"[SKIP] missing test folder: {base_path}")
        return

    zap_org, resp_org, wait_org = extract_data(base_path, func_name, mode, 0)
    zap_opt, resp_opt, wait_opt = extract_data(base_path, func_name, mode, 1)

    x = np.array([0])
    width = 0.35
    offset_org = -0.22
    offset_opt = 0.22

    # Color scheme for stacked plots - dark for org, light for opt
    org_colors = {
        "zap": "#1e40af",      # Dark blue
        "response": "#047857",  # Dark green
        "waiting": "#d97706"    # Dark amber
    }
    opt_colors = {
        "zap": "#60a5fa",      # Light blue
        "response": "#34d399",  # Light green
        "waiting": "#fbbf24"    # Light amber
    }
    # Simple plot colors - blue vs purple
    org_simple_color = "#3b82f6"  # Blue
    opt_simple_color = "#8b5cf6"  # Purple

    # Set style
    plt.style.use('seaborn-v0_8-darkgrid')
    fig, ax = plt.subplots(figsize=(10, 6))
    
    # Set background color
    fig.patch.set_facecolor('#f8fafc')
    ax.set_facecolor('#ffffff')

    if func_name == "de_thread":
        plot_stack(ax, x,
                   zap_org[0], resp_org[0], wait_org[0],
                   org_colors, "org", width, offset_org)

        plot_stack(ax, x,
                   zap_opt[0], resp_opt[0], wait_opt[0],
                   opt_colors, "opt", width, offset_opt)
    else:
        plot_simple(ax, x,
                    zap_org[0], resp_org[0], wait_org[0],
                    org_simple_color, "org", width, offset_org)

        plot_simple(ax, x,
                    zap_opt[0], resp_opt[0], wait_opt[0],
                    opt_simple_color, "opt", width, offset_opt)

    # Styling improvements
    ax.set_xticks([0])
    ax.set_xticklabels([f"Thread {THREAD}"], fontsize=12, fontweight='600')
    ax.set_xlabel("Comparison", fontsize=13, fontweight='600', labelpad=10)
    ax.set_ylabel("Time (ns)", fontsize=13, fontweight='600', labelpad=10)
    
    # Improved title
    title = f"{test_name.replace('_', ' ').title()} | {func_name} | {mode.capitalize()}"
    ax.set_title(title, fontsize=15, fontweight='700', pad=20)

    # Grid styling
    ax.grid(True, axis='y', alpha=0.3, linestyle='--', linewidth=0.8)
    ax.set_axisbelow(True)
    
    # Spine styling
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_linewidth(1.2)
    ax.spines['bottom'].set_linewidth(1.2)
    ax.spines['left'].set_color('#94a3b8')
    ax.spines['bottom'].set_color('#94a3b8')

    # Improved legend
    ax.legend(loc='upper right', frameon=True, shadow=True, 
              fancybox=True, ncol=2, fontsize=10,
              framealpha=0.95, edgecolor='#cbd5e1')
    
    # Tick styling
    ax.tick_params(axis='both', which='major', labelsize=10, 
                   colors='#475569', length=6, width=1.2)

    plt.tight_layout()

    out_dir = f"./results/{test_name}/{THREAD}"
    os.makedirs(out_dir, exist_ok=True)

    out_file = os.path.join(out_dir, f"{func_name}_{mode}.svg")
    plt.savefig(out_file, dpi=150, bbox_inches='tight', facecolor=fig.get_facecolor())
    plt.close()

    print(f"[SAVED] {out_file}")


# -------------------- RUN --------------------

for func in TARGET_FUNCTIONS:
    plot_test_function(test_name, func, "median")
    plot_test_function(test_name, func, "mean")

print(f"[DONE] plots saved under results/{test_name}/{THREAD}/")
