# Generated by GPT

import os
import json
import numpy as np
import matplotlib.pyplot as plt

num_threads = np.array([1, 2, 3, 4, 5])

TESTS = [
    "test_heavy", "test_double_exec", "test_nonmain_exec"
]

TARGET_FUNCTIONS = ["de_thread", "do_execveat_common"]


def find_function(node_list, target):
    for node in node_list:
        if node["function"] == target:
            return node
        res = find_function(node.get("children", []), target)
        if res:
            return res
    return None


def extract_data(base_dir, func_name, mode, opt_on):


    zap, response, waiting = [], [], []

    for n in num_threads:
        if opt_on:
            folder_path = os.path.join(base_dir, str(n), "optimized")
        else:
            folder_path = os.path.join(base_dir, str(n), "original")

        trace_file = os.path.join(folder_path, "traces", "final.json")
        log_file = os.path.join(folder_path, "logs", "final.json")

        if not os.path.exists(trace_file) or not os.path.exists(log_file):
            zap.append(np.nan)
            response.append(np.nan)
            waiting.append(np.nan)
            continue

        with open(trace_file) as f:
            data = json.load(f)

        func_node = find_function(data, func_name)
        zap_node = find_function(data, "zap_other_threads")

        if not func_node or not zap_node:
            zap.append(np.nan)
            response.append(np.nan)
            waiting.append(np.nan)
            continue

        if mode == "median":
            func_total = func_node["inc_ns_median"]
            zap_time = zap_node["inc_ns_median"]
            log_key = "median"
        else:
            func_total = func_node["inc_ns_avg"]
            zap_time = zap_node["inc_ns_avg"]
            log_key = "avg"

        with open(log_file) as f:
            log_data = json.load(f)

        response_time = log_data[log_key]
        waiting_time = func_total - (zap_time + response_time)

        zap.append(zap_time)
        response.append(response_time)
        waiting.append(waiting_time)

    return np.array(zap), np.array(response), np.array(waiting)


# ---------------- STACKED (for de_thread) ----------------
def plot_stack(ax, xpos, zap, resp, wait, colors, label, bar_width):

    ax.bar(xpos, zap, bar_width, color=colors["zap"], 
           edgecolor='white', linewidth=2, alpha=0.9,
           label=f"zap ({label})")
    ax.bar(xpos, resp, bar_width, bottom=zap, color=colors["response"],
           edgecolor='white', linewidth=2, alpha=0.9,
           label=f"response ({label})")
    ax.bar(xpos, wait, bar_width, bottom=zap + resp, color=colors["waiting"],
           edgecolor='white', linewidth=2, alpha=0.9,
           label=f"waiting ({label})")

    for xi, z, r, w in zip(xpos, zap, resp, wait):

        if np.isnan(z) or np.isnan(r) or np.isnan(w):
            ax.text(xi, 0, "MISSING",
                    ha='center', va='bottom',
                    rotation=90, fontsize=10,
                    color='#ef4444', fontweight='bold')
            continue

        total = z + r + w if (z + r + w) != 0 else 1

        def add(y, val):
            if val <= 0:
                return
            ax.text(
                xi, y,
                f"{val:.0f}\n({val/total*100:.1f}%)",
                ha='center', va='center', fontsize=9,
                fontweight='600', color='white',
                bbox=dict(boxstyle='round,pad=0.3', facecolor='black', 
                         alpha=0.35, edgecolor='none')
            )

        add(z / 2, z)
        add(z + r / 2, r)
        add(z + r + w / 2, w)


# ---------------- SIMPLE BAR (for execveat) ----------------
def plot_simple(ax, xpos, zap, resp, wait, color, label, bar_width):

    total = zap + resp + wait

    ax.bar(xpos, total, bar_width, color=color,
           edgecolor='white', linewidth=2, alpha=0.9,
           label=f"total ({label})")

    for xi, t in zip(xpos, total):

        if np.isnan(t):
            ax.text(xi, 0, "MISSING",
                    ha='center', va='bottom',
                    rotation=90, fontsize=10,
                    color='#ef4444', fontweight='bold')
            continue

        ax.text(
            xi, t + t * 0.02,
            f"{t:.0f}",
            ha='center', va='bottom', fontsize=10,
            fontweight='700', color=color
        )


def plot_test_function(test_name, func_name, mode):

    path = f"./results/{test_name}"
    opt_path = f"./results/test/opt/{test_name}"

    if not os.path.exists(path):
        print(f"[SKIP] {test_name}")
        return

    print(f"[INFO] {test_name} | {func_name} | {mode}")

    zap_org, resp_org, wait_org = extract_data(path, func_name, mode, 0)
    zap_opt, resp_opt, wait_opt = extract_data(path, func_name, mode, 1)

    x = np.arange(len(num_threads))
    bar_width = 0.35

    # Color scheme for stacked plots - dark for org, light for opt
    org_colors = {
        "zap": "#1e40af",      # Dark blue
        "response": "#047857",  # Dark green
        "waiting": "#d97706"    # Dark amber
    }
    opt_colors = {
        "zap": "#60a5fa",      # Light blue
        "response": "#34d399",  # Light green
        "waiting": "#fbbf24"    # Light amber
    }
    # Simple plot colors - blue vs purple
    org_simple_color = "#3b82f6"  # Blue
    opt_simple_color = "#8b5cf6"  # Purple

    # Set style
    plt.style.use('seaborn-v0_8-darkgrid')
    fig, ax = plt.subplots(figsize=(16, 7))
    
    # Set background color
    fig.patch.set_facecolor('#f8fafc')
    ax.set_facecolor('#ffffff')

    # ---------------- SELECT PLOT TYPE ----------------
    if func_name == "de_thread":

        plot_stack(
            ax,
            x - bar_width/2,
            zap_org, resp_org, wait_org,
            org_colors, "org", bar_width
        )

        plot_stack(
            ax,
            x + bar_width/2,
            zap_opt, resp_opt, wait_opt,
            opt_colors, "opt", bar_width
        )

    else:  # do_execveat_common → simple bar

        plot_simple(
            ax,
            x - bar_width/2,
            zap_org, resp_org, wait_org,
            org_simple_color,
            "org",
            bar_width
        )

        plot_simple(
            ax,
            x + bar_width/2,
            zap_opt, resp_opt, wait_opt,
            opt_simple_color,
            "opt",
            bar_width
        )

    # ---------------- AXIS STYLING ----------------
    ax.set_xticks(x)
    ax.set_xticklabels([str(n) for n in num_threads], fontsize=11, fontweight='600')
    ax.set_xlabel("Number of Threads", fontsize=13, fontweight='600', labelpad=10)
    ax.set_ylabel("Time (ns)", fontsize=13, fontweight='600', labelpad=10)
    
    # Improved title
    title = f"{test_name.replace('_', ' ').title()}: {func_name} ({mode.capitalize()}) Comparison"
    ax.set_title(title, fontsize=15, fontweight='700', pad=20)

    # Grid styling
    ax.grid(True, axis='y', alpha=0.3, linestyle='--', linewidth=0.8)
    ax.set_axisbelow(True)
    
    # Spine styling
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_linewidth(1.2)
    ax.spines['bottom'].set_linewidth(1.2)
    ax.spines['left'].set_color('#94a3b8')
    ax.spines['bottom'].set_color('#94a3b8')

    # Improved legend
    handles, labels = ax.get_legend_handles_labels()
    unique = dict(zip(labels, handles))
    ax.legend(unique.values(), unique.keys(), 
              loc='upper right', frameon=True, shadow=True, 
              fancybox=True, ncol=2, fontsize=10,
              framealpha=0.95, edgecolor='#cbd5e1')
    
    # Tick styling
    ax.tick_params(axis='both', which='major', labelsize=10, 
                   colors='#475569', length=6, width=1.2)

    plt.tight_layout()

    out_dir = f"./plots/{test_name}"
    os.makedirs(out_dir, exist_ok=True)

    out_file = os.path.join(out_dir, f"{func_name}_comparison_{mode}.svg")
    plt.savefig(out_file, dpi=150, bbox_inches='tight', facecolor=fig.get_facecolor())
    plt.close()

    print(f"[SAVED] {out_file}")


# ---------------- RUN ----------------
for t in TESTS:
    for func in TARGET_FUNCTIONS:
        plot_test_function(t, func, "median")
        plot_test_function(t, func, "mean")

print(
        "[WARNING] comparison plot supports only 1 to 5 threads. "
        "Any additional thread data will be ignored. "
        "Please check the respective result directory for extra threads."
    )